In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore")

ModuleNotFoundError: No module named 'pandas'

In [2]:
df = pd.read_csv('homeprices.csv')

In [3]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [4]:
df.bedrooms.fillna(df.bedrooms.median(),inplace=True)

In [5]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
x_df = df.drop(['price'],axis=1)
y_df = df.price

In [7]:
x_df

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [8]:
y_df

0    550000
1    565000
2    610000
3    595000
4    760000
5    810000
Name: price, dtype: int64

In [9]:
lr = LinearRegression()
lr.fit(x_df,y_df)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [10]:
lr.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [11]:
lr.intercept_

221323.00186540408

In [ ]:
y =  112.06244194*area + 23388.88007794*bedrooms -3231.71790863*age

In [13]:
lr.predict([[3000,3,40]])

array([498408.25158031])

In [14]:
 112.06244194*3000 + 23388.88007794*3 -3231.71790863*40

277085.24970862

In [16]:
 (112.06244194*3000) + (23388.88007794*3) -(3231.71790863*40) + 221323.00186540400

498408.251574024

In [17]:
from pandas_profiling import ProfileReport

ModuleNotFoundError: No module named 'pandas_profiling'

In [18]:
lr.predict([[7430,6,5]])

array([1178121.63641993])